### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by orschiro** [kkamperschroer/NewTabNotes#4]
Dear @kkamperschroer,

Thanks for your extension. 

I would like to try it. However, the installation fails:

![image](https://cloud.githubusercontent.com/assets/170947/15847248/a383c480-2c84-11e6-8e69-47df184a0163.png)

Any ideas?

Thankfully,

~Robert

**Comment by kylekampy** [comment]
Thanks for the repot, Robert! I apologize, I actually have been aware of this issue but just haven't found the time to fix it. I will hopefully get to it soon!

**Comment by orschiro** [comment]
You're welcome.

Great that it's on your to-do list! :smiley: 

Thankfully,

~Robert
